const VIEW_TODAY = 'VIEW_TODAY'
const VIEW_PREV = 'VIEW_PREV'
const VIEW_NEXT = 'VIEW_NEXT'
const CHANGE_WINDOW = 'CHANGE_WINDOW'

const RECEIVE_EVENT = 'RECEIVE_EVENT'

const ADD_OPTION = 'ADD_OPTION'
const DELETE_OPTION = 'DELETE_OPTION'

const CHANGE_TIME = 'CHANGE_TIME'
const CHANGE_DATE = 'CHANGE_DATE'
const CHANGE_DURATION = 'CHANGE_DURATION'
const CHANGE_LOCATION = 'CHANGE_LOCATION'

const ADD_USER = 'ADD_USER'

const ADD_EMAIL = 'ADD_EMAIL'
const DELETE_EMAIL = 'DELETE_EMAIL'

const SUBMIT_PROPOSAL = 'SUBMIT_PROPOSAL'

export {
  VIEW_TODAY,
  VIEW_PREV,
  VIEW_NEXT,
  CHANGE_WINDOW,
  RECEIVE_EVENT,
  ADD_OPTION,
  DELETE_OPTION,
  CHANGE_TIME,
  CHANGE_DATE,
  CHANGE_DURATION,
  CHANGE_LOCATION,
  ADD_USER,
  ADD_EMAIL,
  DELETE_EMAIL,
  SUBMIT_PROPOSAL
}
