const VIEW_TODAY = 'VIEW_TODAY'
const VIEW_PREV = 'VIEW_PREV'
const VIEW_NEXT = 'VIEW_NEXT'
const CHANGE_WINDOW = 'CHANGE_WINDOW'

const RECEIVE_EVENT = 'RECEIVE_EVENT'

const ADD_VOTE = 'ADD_VOTE'
const DELETE_VOTE = 'DELETE_VOTE'
const RECEIVE_VOTES = 'RECEIVE_VOTES'

const CHANGE_TIME_FROM = 'CHANGE_TIME_FROM'
const CHANGE_TIME_TO = 'CHANGE_TIME_TO'
const CHANGE_DATE = 'CHANGE_DATE'

export {
  VIEW_TODAY,
  VIEW_PREV,
  VIEW_NEXT,
  CHANGE_WINDOW,
  RECEIVE_EVENT,
  ADD_VOTE,
  DELETE_VOTE,
  RECEIVE_VOTES,
  CHANGE_TIME_FROM,
  CHANGE_TIME_TO,
  CHANGE_DATE
}
