var Sendgrid = require("sendgrid-web");
var dotenv = require('dotenv').config();
var sendgrid = new Sendgrid({
  user: process.env.SENDGRID_USERNAME,
  key: process.env.SENDGRID_PASSWORD
});

exports.sendToken = function(address, token, callback){
  if (!address || !token) throw new Error("Email needs address and token to send.");

  var HTML="";
  HTML += "<!DOCTYPE html>";
  HTML += "<html>";
  HTML += "<head>";
  HTML += "  <meta http-equiv=\"Content-Type\" content=\"text\/html; charset=utf-8\" \/>";
  HTML += "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1\" \/>";
  HTML += "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" \/>";
  HTML += "";
  HTML += "  <style type=\"text\/css\">";
  HTML += "  body {";
  HTML += "    color: #999999;";
  HTML += "  }";
  HTML += "  body a {";
  HTML += "    color: #1188e6;";
  HTML += "    text-decoration: none;";
  HTML += "  }";
  HTML += "  p { margin: 0; padding: 0; }";
  HTML += "  table[class=\"wrapper\"] {";
  HTML += "    width:100% !important;";
  HTML += "    table-layout: fixed;";
  HTML += "    -webkit-font-smoothing: antialiased;";
  HTML += "    -webkit-text-size-adjust: 100%;";
  HTML += "    -moz-text-size-adjust: 100%;";
  HTML += "    -ms-text-size-adjust: 100%;";
  HTML += "  }";
  HTML += "  img[class=\"max-width\"] {";
  HTML += "    max-width: 100% !important;";
  HTML += "  }";
  HTML += "  @media screen and (max-width:480px) {";
  HTML += "    .preheader .rightColumnContent,";
  HTML += "    .footer .rightColumnContent {";
  HTML += "        text-align: left !important;";
  HTML += "    }";
  HTML += "    .preheader .rightColumnContent div,";
  HTML += "    .preheader .rightColumnContent span,";
  HTML += "    .footer .rightColumnContent div,";
  HTML += "    .footer .rightColumnContent span {";
  HTML += "      text-align: left !important;";
  HTML += "    }";
  HTML += "    .preheader .rightColumnContent,";
  HTML += "    .preheader .leftColumnContent {";
  HTML += "      font-size: 80% !important;";
  HTML += "      padding: 5px 0;";
  HTML += "    }";
  HTML += "    table[class=\"wrapper-mobile\"] {";
  HTML += "      width: 100% !important;";
  HTML += "      table-layout: fixed;";
  HTML += "    }";
  HTML += "    img[class=\"max-width\"] {";
  HTML += "      height: auto !important;";
  HTML += "    }";
  HTML += "    a[class=\"bulletproof-button\"] {";
  HTML += "      display: block !important;";
  HTML += "      width: auto !important;";
  HTML += "      font-size: 80%;";
  HTML += "      padding-left: 0 !important;";
  HTML += "      padding-right: 0 !important;";
  HTML += "    }";
  HTML += "    \/\/ 2 columns";
  HTML += "    #templateColumns{";
  HTML += "        width:100% !important;";
  HTML += "    }";
  HTML += "";
  HTML += "    .templateColumnContainer{";
  HTML += "        display:block !important;";
  HTML += "        width:100% !important;";
  HTML += "        padding-left: 0 !important;";
  HTML += "        padding-right: 0 !important;";
  HTML += "    }";
  HTML += "  }";
  HTML += "  <\/style>";
  HTML += "  <style>";
  HTML += "  body, p, div { font-family: arial,sans-serif; }";
  HTML += "<\/style>";
  HTML += "  ";
  HTML += "<\/head>";
  HTML += "<body yahoofix=\"true\" style=\"min-width: 100%; margin: 0; padding: 0; font-size: 14pxpx; font-family: arial,sans-serif; color: #999999; background-color: #FFFFFF; color: #999999;\" data-attributes='%7B%22dropped%22%3Atrue%2C%22bodybackground%22%3A%22%23FFFFFF%22%2C%22bodyfontname%22%3A%22arial%2Csans-serif%22%2C%22bodytextcolor%22%3A%22%23000000%22%2C%22bodylinkcolor%22%3A%22%231188e6%22%2C%22bodyfontsize%22%3A%2214px%22%7D'>";
  HTML += "  <center class=\"wrapper\">";
  HTML += "    <div class=\"webkit\">";
  HTML += "      <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"100%\" class=\"wrapper\" bgcolor=\"#FFFFFF\">";
  HTML += "      <tr><td valign=\"top\" bgcolor=\"#FFFFFF\" width=\"100%\">";
  HTML += "            <table width=\"100%\" role=\"content-container\" class=\"outer\" data-attributes='%7B%22dropped%22%3Atrue%2C%22containerpadding%22%3A%220%2C0%2C0%2C0%22%2C%22containerwidth%22%3A600%2C%22containerbackground%22%3A%22%23FFFFFF%22%7D' align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
  HTML += "              <tr>";
  HTML += "                <td width=\"100%\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
  HTML += "                  <tr>";
  HTML += "                    <td>";
  HTML += "                    <!--[if (gte mso 9)|(IE)]>";
  HTML += "                      <table width=\"600\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">";
  HTML += "                        <tr>";
  HTML += "                          <td>";
  HTML += "                            <![endif]-->";
  HTML += "                              <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width: 100%; max-width:600px;\" align=\"center\">";
  HTML += "                                <tr><td role=\"modules-container\" style=\"padding: 0px 0px 0px 0px; color: #999999; text-align: left;\" bgcolor=\"#FFFFFF\" width=\"100%\" align=\"left\">";
  HTML += "                                  <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" width=\"100%\" style=\"display:none !important; visibility:hidden; opacity:0; color:transparent; height:0; width:0;\" class=\"module preheader preheader-hide\" role=\"module\" data-type=\"preheader\">";
  HTML += "  <tr><td role=\"module-content\"><p><\/p><\/td><\/tr>";
  HTML += "<\/table>";
  HTML += "<table class=\"module\" role=\"module\" data-type=\"text\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"  width=\"100%\" style=\"table-layout: fixed;\" data-attributes='%7B%22dropped%22%3Atrue%2C%22child%22%3Afalse%2C%22padding%22%3A%220%2C0%2C0%2C0%22%2C%22containerbackground%22%3A%22%23ffffff%22%7D'>";
  HTML += "<tr>";
  HTML += "  <td role=\"module-content\"  valign=\"top\" height=\"100%\" style=\"padding: 0px 0px 0px 0px;\" bgcolor=\"#ffffff\"><h2 style=\"text-align: center;\"><span style=\"font-size:18px;\">Please click below to verify your email and access your <span style=\"color:#CC4668;\"><strong>Squad <\/strong><\/span>profile<\/span><\/h2> <\/td>";
  HTML += "<\/tr>";
  HTML += "<\/table>";
  HTML += "<table class=\"module\" role=\"module\" data-type=\"button\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"table-layout: fixed;\" data-attributes='%7B%22dropped%22%3Atrue%2C%22borderradius%22%3A100%2C%22buttonpadding%22%3A%2218%2C24%2C18%2C24%22%2C%22text%22%3A%22Start%2520Your%2520Squad%22%2C%22alignment%22%3A%22center%22%2C%22fontsize%22%3A20%2C%22url%22%3A%22%22%2C%22height%22%3A%22%22%2C%22width%22%3A%22%22%2C%22containerbackground%22%3A%22%23ffffff%22%2C%22padding%22%3A%220%2C0%2C0%2C0%22%2C%22buttoncolor%22%3A%22%23cc4668%22%2C%22textcolor%22%3A%22%23ffffff%22%2C%22bordercolor%22%3A%22%23CC4668%22%7D'>";
  HTML += "<tr>";
  HTML += "  <td style=\"padding: 0px 0px 0px 0px;\" align=\"center\" bgcolor=\"#ffffff\">";
  HTML += "    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"wrapper-mobile\">";
  HTML += "      <tr>";
  HTML += "        <td align=\"center\" style=\"-webkit-border-radius: 100px; -moz-border-radius: 100px; border-radius: 100px; font-size: 20px;\" bgcolor=\"#cc4668\">";
  HTML += "          <a href=" + "http://localhost:8080/u/register/" + token + "\" class=\"bulletproof-button\" target=\"_blank\" style=\"height: px; width: px; font-size: 20px; line-height: px; font-family: Helvetica, Arial, sans-serif; color: #ffffff; padding: 18px 24px 18px 24px; text-decoration: none; color: #ffffff; text-decoration: none; -webkit-border-radius: 100px; -moz-border-radius: 100px; border-radius: 100px; border: 1px solid #CC4668; display: inline-block;\">Start Your Squad<\/a>";
  HTML += "        <\/td>";
  HTML += "      <\/tr>";
  HTML += "    <\/table>";
  HTML += "  <\/td>";
  HTML += "<\/tr>";
  HTML += "<\/table>";
  HTML += "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" width=\"100%\" class=\"module footer\" role=\"module\" data-type=\"footer\" data-attributes='%7B%22dropped%22%3Atrue%2C%22columns%22%3A1%2C%22padding%22%3A%2210%2C5%2C10%2C5%22%2C%22containerbackground%22%3A%22%23ffffff%22%7D'>";
  HTML += "  <tr><td style=\"padding: 10px 5px 10px 5px;\" bgcolor=\"#ffffff\">";
  HTML += "    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" width=\"100%\">";
  HTML += "      <tr role=\"module-content\">";
  HTML += "        ";
  HTML += "        <td align=\"center\" valign=\"top\" width=\"100%\" height=\"100%\" class=\"templateColumnContainer\">";
  HTML += "          <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" height=\"100%\">";
  HTML += "            <tr>";
  HTML += "              <td class=\"leftColumnContent\" role=\"column-one\" height=\"100%\" style=\"height:100%;\"><table class=\"module\" role=\"module\" data-type=\"text\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"  width=\"100%\" style=\"table-layout: fixed;\" data-attributes='%7B%22dropped%22%3Atrue%2C%22child%22%3Afalse%2C%22padding%22%3A%220%2C0%2C0%2C0%22%2C%22containerbackground%22%3A%22%23ffffff%22%7D'>";
  HTML += "<tr>";
  HTML += "  <td role=\"module-content\"  valign=\"top\" height=\"100%\" style=\"padding: 0px 0px 0px 0px;\" bgcolor=\"#ffffff\"><div style=\"font-size:12px;line-height:150%;margin:0;text-align:center;\">&nbsp;<\/div>  <div style=\"font-size:12px;line-height:150%;margin:0;text-align:center;\">This email was sent by: " + "Squad" + " admin@squadup.io" + "<\/div> <\/td>";
  HTML += "<\/tr>";
  HTML += "<\/table>";
  HTML += "<\/td>";
  HTML += "            <\/tr>";
  HTML += "          <\/table>";
  HTML += "        <\/td>";
  HTML += "        ";
  HTML += "      <\/tr>";
  HTML += "    <\/table>";
  HTML += "  <\/td><\/tr>";
  HTML += "<\/table>";
  HTML += "";
  HTML += "                                <\/tr><\/td>";
  HTML += "                              <\/table>";
  HTML += "                    <\/td>";
  HTML += "                  <\/tr>";
  HTML += "                <\/table><\/td>";
  HTML += "              <\/tr>";
  HTML += "            <\/table>";
  HTML += "      <\/tr><\/td>";
  HTML += "      <\/table>";
  HTML += "    <\/div>";
  HTML += "  <\/center>";
  HTML += "<\/body>";
  HTML += "<\/html>";
  if (token) {
    sendgrid.send({
      to: address,
      from: 'admin@squadup.io',
      subject: 'Please verify your account, and thanks for Squading Up! ',
      html: HTML
    }, function (err) {
      callback(err);
    });
  }
}
